version: '3'

services:
  app:
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    networks:
      - app_network

  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge