version: '3'

services:
  app:
    build: .
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    networks:
      - app_network

  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificates:/etc/nginx/certificates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certificates:/etc/letsencrypt
      - ./certificates-data:/data/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 2073600; done'"

networks:
  app_network:
    driver: bridge